### ISSUE TITLE
scripts/preprocess.py should sort tokens lexicographically

### ISSUE THREAD

**Issue by AlekzNet** [jcjohnson/torch-rnn#43] opened 2016-03-22 23:43 UTC
Currently the indexes are assigned to tokens on the first occurrence basis. If the text is changed (think of fixing a typo or training a pre-trained model on a different corpus) the indexes might be reassigned what will break subsequent training initialized from a checkpoint.

**Comment by dgcrouse** [comment] 2017-04-27 04:56
Duplicate of #12. We are addressing this by creating a script that encodes new data using an existing JSON schema. This is faster and more space-friendly, esp. for non-text datasets.

**Closed by dgcrouse** 2017-04-27 04:56 UTC
Labels: duplicate
