### ISSUE TITLE
`sample -start_text` seems to fail support unicode.

### ISSUE THREAD

**Issue by vi** [jcjohnson/torch-rnn#133] opened 2016-08-13 21:39 UTC
Specifying UTF-8 to `-start_text` fails:

```
/home/vi/home/deepstyle/r/torch/install/bin/luajit: /home/vi/home/deepstyle/r/torch-rnn/LanguageModel.lua:129: Got invalid idx
stack traceback:
	[C]: in function 'assert'
	/home/vi/home/deepstyle/r/torch-rnn/LanguageModel.lua:129: in function 'encode_string'
	/home/vi/home/deepstyle/r/torch-rnn/LanguageModel.lua:174: in function 'sample'
	/home/vi/home/deepstyle/r/torch-rnn/sample.lua:41: in main chunk
	[C]: in function 'dofile'
	...le/r/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```

**Comment by smartynov** [comment] 2016-08-14 23:00
Is'n it a duplicate of #47 ?

**Comment by vi** [comment] 2016-08-15 20:28
Yes.

**Closed** 2016-08-15 20:28 UTC
